language: python
python:
- '3.6'
script:
- pip3 install -r requirements.txt
deploy:
  provider: lambda
  function_name: strideHours
  region: us-east-2
  role: arn:aws:iam::188709785926:role/service-role/stacey
  runtime: python3.6
  handler_name: lambda_handler
  module_name: TimesheetLoad
  zip:  ${TRAVIS_BUILD_DIR}/build/distributions/TimesheetLoad.zip
  access_key_id:
    secure: Lp5Rd0MGpJUofJkF8ynfeY96yeqAYHk8q+esaqz31JJoriONJbEASgODfBZWhK3/92h8zQovfW+WyFozqoCgdgTH0itJkMDz4ePI159A0SIsK9NPRGrGK2C1SmEmHGUfHiUMJJawQpIz4RchT43XRsfCN8+h8ssHC9YZVsOC6/ea8zhVVydfQFLqrHCfWCUk5yu0hIwe53v2W+VtPejTnJ3F3w9a3XHVkIDCmVlmCNwZjCXmpFnJk8074r361yuklmZuquhK4MPLYFNPrhyslWAegd+Vm3c4I8yeS26GYpzEvcJgnSB1RiXVlEBdkK7SUyLM4BUMKfKZED4zntfgnF0NngyWgejlYFm5aBWwNU0Ma8A0cIKDUtSEB7PHURhQ4I11Ig+XLcwMjGVE1bcsJQG9VrlKQw2f2qv55y+PpvoqID2BSGerPhEw9d8QcJcd4+8gNhb6AViJEV3M0tY/BVFm82UiVedJKJUKDSrHeck9tht1zTyx6edxDywbWcygGkBnAF7ku29xylxxNb5dN+rX4+1p2yEZtPoT+hNWeu4lLsTZInJDnoymP0gADUoyvNy+5oG3Yqe8uW5ST8uotABxK4DHnfdaIrrov9VoMy/w/BSpKoI2Zua0yRWFdz2wdv8G8HIE3r/S4gFuWFuGlU5DXZdNLGCb0Rk3QoPbGk0=
  secret_access_key:
    secure: 0ekNND+rg2ZMC5+Mcb2KojAKg6IezV8+0UoLehurPPpyByKGHbdXTHEC3oRczS9L9a45B14/rcnAxBjMOKFclgDDasjSfYv78S6ja9BpsQTuiMxVRwi4Dh+NOS6WYOvltGLp4I3nb19nFyUwRx1AyJQgEdi8ujl1reEJRjOrxQusCrryxOo9ORHPM4m5Zb8P4ihuo8FdSHi4RY8jb0mvr0gICcaFy+Qs5vqLnN59Kntr1LqI0AybZFr9bslWxu4veKX4Dal8WomLNCti+rJz9Q+Pd9Wc/Upqq0HcvC/UZPKF5GjVcl5B51p0XSfITajhy/o1pxNryqsenrJrxY0zG4YSBkP4arGCjVRHD0FgozWf/wq/gmyQ2UHg8BJ7xTOotlQ24poBkgMhPWhkKmdlFvC2GHvLibAPlZaVBdcHw+gIc5l7SeXMAlfzD32a3UV20zJYPkT/nHvzFWIb7jN8a55REQxqoo7Bz8Om6vW4r7ooKag9OXvYUiLv19Gifxarc6zDG5GpmLKtz2ZOD/BgjZbYzHdzM9mkmdBwqSb4bHdvLnIxLGRjvmiJ8BXO7Iuog9+hOFedJlHpV5++yZgn3kZoHxkbISJz5KHTIHR6eucyn1j+t9h4JxdD0474gv10wMqG/v6hdXYejWttUhCN+aGHfv8N+RBFUNM20UzNTFE=
  on:
    repo: swatro/TimesheetLoad
